### ISSUE TITLE
list facets in a consistent order - we've ordered alphabetically

### ISSUE THREAD

**Issue by CathLass** [DFE-Digital/search-prototype#59]
CL, AW 18/10/24
Ordering The facets by name has to be done programmatically
**For Facet values**, you can order by count or alphabetically:
Order by Value (alphabetical order)
You can request the facet values to be sorted alphabetically by setting the sort option in the facet expression. This overrides the default behaviour of sorting by count.

To order facets by value (alphabetically):
{
    "facets": [
        "category,sort:value"
    ]
}
sort:value - sorts the facets alphabetically

----------------------------------------------------------------------
Antony Oakes - 16/10/24 14:14
Through many runs of my automated tests in recent weeks alongside the implemented facets I have noticed that they sometimes come back in a different order (not every request results in a different order). 

We have `Phase of education` and `Establishment status` filter headings.
Sometimes `Phase of education` is returned first, other times `Establishment status` is returned first.

@spanersoraferty wonders whether this is something in Azure AI Search.

**Comment by antk43** [comment]
The order of the facets appears to be consistent now.
